services:
  redis:
    image: "redis:alpine"
    expose:
      - "6379"

  bot:
    build:
      context: .
      target: prod-bot
    depends_on:
      - redis
    expose:
      - "8000"

  page:
    build:
      context: .
      target: prod-page
    depends_on:
      - bot
    ports:
      - "3000:3000"
